services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build: .
    command: python producer.py
    depends_on:
      - rabbitmq
  consumer:
    build: .
    command: python consumer.py
    depends_on:
      - rabbitmq